### ISSUE TITLE
problem when import gamera

### ISSUE THREAD

**Issue by OneOverSeven** [hsnr-gamera/gamera-4#11]
Hi,

I’m working on a project and I would like to test your software which seems wonderful.

I posted “Issues” which are not really issues but simply missing libraries and things like that, so that other people that encounter the same problems can find out quickly how to get what they need.

I followed the instructions from the following page: https://gamera.informatik.hsnr.de/docs/gamera-docs/install.html

$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

I Installed all the required libraries and launched “python3 setup.py build” and it compiles.

But after that, when I simply try to import gamera I get:

$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gamera
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gamera'
>>>

and when I run hello_world.py from the examples folder I get:

$ python3 hello_world.py
Traceback (most recent call last):
  File "hello_world.py", line 3, in <module>
    from gamera.core import *
ModuleNotFoundError: No module named 'gamera'

I tried on a CentOs, Ubuntu and a Windows 10 machine and get the same message. 

Sorry if it is something obvious but I don't know what to do to get it work. I'm certainly doing something wrong but I don't know what. Could you help me with that please?

**Comment by Cyperghost** [comment]
You need to install the gamera module, with `python3 setup.py install`

**Comment by OneOverSeven** [comment]
Hooo...

That is much better indeed. 

Really sorry, thank you very much!!
