### ISSUE TITLE
A forum needed?

### ISSUE THREAD

**Issue by jsbien** [hsnr-gamera/gamera-4#29]
Is the mailing list completely dead? If so, it would be useful to switch on the relatively new github feature, i.e. discussions - cf. e.g. 
https://github.com/psb1558/Junicode-New/discussions

**Comment by cdalitz** [comment]
Thanks for the hint! I was not aware of this feature, but now it is activated. It seems to be available per repository (not per organization), and I have thus only created *one* discussion in *gamera-4* (to avoid confusion where to post).
