### ISSUE TITLE
Deprecation warnings for VIGRA

### ISSUE THREAD

**Issue by FriedrichFroebel** [hsnr-gamera/gamera-4#42]
Building the package on Ubuntu 20.04 with GCC 9.30 reports some warnings for the included *vigra* library like the following ones:

```
In file included from include/vigra/colorconversions.hxx:45,
                 from include/pixel.hpp:47,
                 from include/gamera.hpp:53,
                 from include/gameramodule.hpp:25,
                 from src/gameracore/gameramodule.cpp:23:
include/vigra/functortraits.hxx:166:31: warning: ‘template<class _Operation> class std::binder1st’ is deprecated [-Wdeprecated-declarations]
  166 | VIGRA_DEFINE_STL_FUNCTOR(std::binder1st, VigraTrueType, VigraFalseType)
      |                               ^~~~~~~~~
include/vigra/functortraits.hxx:131:21: note: in definition of macro ‘VIGRA_DEFINE_STL_FUNCTOR’
  131 | class FunctorTraits<name<T> > \
      |                     ^~~~
In file included from /usr/include/c++/9/bits/stl_function.h:1392,
                 from /usr/include/c++/9/string:48,
                 from /usr/include/c++/9/stdexcept:39,
                 from include/vigra/config.hxx:42,
                 from include/vigra/rgbvalue.hxx:44,
                 from include/pixel.hpp:46,
                 from include/gamera.hpp:53,
                 from include/gameramodule.hpp:25,
                 from src/gameracore/gameramodule.cpp:23:
/usr/include/c++/9/backward/binders.h:108:11: note: declared here
  108 |     class binder1st
      |           ^~~~~~~~~
In file included from include/vigra/colorconversions.hxx:45,
                 from include/pixel.hpp:47,
                 from include/gamera.hpp:53,
                 from include/gameramodule.hpp:25,
                 from src/gameracore/gameramodule.cpp:23:
include/vigra/functortraits.hxx:167:31: warning: ‘template<class _Operation> class std::binder2nd’ is deprecated [-Wdeprecated-declarations]
  167 | VIGRA_DEFINE_STL_FUNCTOR(std::binder2nd, VigraTrueType, VigraFalseType)
      |                               ^~~~~~~~~
include/vigra/functortraits.hxx:131:21: note: in definition of macro ‘VIGRA_DEFINE_STL_FUNCTOR’
  131 | class FunctorTraits<name<T> > \
      |                     ^~~~
In file included from /usr/include/c++/9/bits/stl_function.h:1392,
                 from /usr/include/c++/9/string:48,
                 from /usr/include/c++/9/stdexcept:39,
                 from include/vigra/config.hxx:42,
                 from include/vigra/rgbvalue.hxx:44,
                 from include/pixel.hpp:46,
                 from include/gamera.hpp:53,
                 from include/gameramodule.hpp:25,
                 from src/gameracore/gameramodule.cpp:23:
/usr/include/c++/9/backward/binders.h:143:11: note: declared here
  143 |     class binder2nd
      |           ^~~~~~~~~
```

If I understand correctly, this should be fixed in the upstream version of *vigra*: https://github.com/ukoethe/vigra/pull/500.

According to https://github.com/hsnr-gamera/gamera-4/blob/master/include/vigra/README *gamera-4* bundles a copy of *vigra*. We might want to update the whole copy as well or use a submodule-based approach if possible.

**Comment by cdalitz** [comment]
With version 1.7.0, VIGRA changed the meaning from angles from counter-clockwise to clockwise, which was an incompatible change that might break end user applications. Before switsching to a newer version of VIGRA, we must thus first find all instances where angles are passed to VIGRA and invert their signs. Or we just ignore this and let and users scratch their heads.

**Comment by FriedrichFroebel** [comment]
I have to admit that I am neither familiar with Gamera nor VIGRA in enough detail to comment on which approach should be preferred here. In general I prefer not to bundle external sources wherever possible, as these usually are out-of-date.

Judging from your description, the easiest approach would be to perform the replacements from the upstream PR in our bundled copy? With this we avoid the hassle of dealing with the incompatible angle behaviour for now, leaving this for a possible upgrade later on.

**Comment by cdalitz** [comment]
Yes, merging these changes into the copy of VIGRA 1.6 and documenting this in a README of the bundled copy would be an option. OTOH, if it's only a wraning and no error, I do nt think that it is worth the trouble.

The reason for bundling some libraries with Gamera is to make it easier to compile on non-Linux platforms.

**Comment by FriedrichFroebel** [comment]
Fixing these warnings actually turned out to be rather straightforward, as this affects less than 10 lines. I will send a PR for this as soon as I have isolated the corresponding changes from my latest tests.
