### ISSUE TITLE
Uses deprecated PyObject_CheckReadBuffer and PyObject_AsReadBuffer

### ISSUE THREAD

**Issue by FriedrichFroebel** [hsnr-gamera/gamera-4#43]
When building the package on Python 3.8, some deprecation warnings are raised due to using the old buffer protocol (https://docs.python.org/3/c-api/objbuffer.html).

As already mentioned in the TODO file, these should be replaced to guarantee compatibility to future Python versions, although the corresponding methods are still part of the current development version according to https://github.com/python/cpython/blob/main/Include/abstract.h.

**Comment by FriedrichFroebel** [comment]
Will be fixed by #61 as well.

**Comment by cdalitz** [comment]
This should be fixed with the latest commit.
