### ISSUE TITLE
When I browse this new commit meaningful pictures are replaced by empty pictures?

### ISSUE THREAD

**Issue by rmast** [hsnr-gamera/gamera-4#45]
https://github.com/hsnr-gamera/gamera-4/commit/fbc2d90adc76264c8c7c3ca3cca04a3ca17e93dd

**Comment by cdalitz** [comment]
Thanks for spotting this. There seems to be an error in to_numpy, from_numpy, _to_raw_string, or _from_raw_string.

We must have a look into this.

**Comment by cdalitz** [comment]
This is now fixed.

**Comment by rmast** [comment]
This image is not repaired by the fix:
https://github.com/hsnr-gamera/gamera-4/blob/master/doc/html/images/to_numpy_plugin_00_01.png

**Comment by AShkolnik** [comment]
In this case only the fix was merged and not the generated images by gendoc.py.
Do you still get the same images when you run gendoc.py by yourself?

**Comment by cdalitz** [comment]
> This image is not repaired by the fix: https://github.com/hsnr-gamera/gamera-4/blob/master/doc/html/images/to_numpy_plugin_00_01.png

Thanks for spotting this. I forgot to update the documentation. This is now fixed.
