### ISSUE TITLE
image.to_grey16() outputs fully black images

### ISSUE THREAD

**Issue by EMZEDI** [hsnr-gamera/gamera-4#48]
---
name: 🐞Bug
about: Conversion .to_grey16() method
title: '.to_grey16() outputs fully black images'
---

### Current Behavior:
I am using Gamera4 to convert RGB images to Greyscale16 format. I have tried more than 10 datasets and all output fully black images using the .to_grey16() method in the image conversions. The same thing happens with Gamera3. I am wondering where this problem is coming from and if this has ever happened previously. 

### Expected Behavior:
The method is supposed to return a black and white image in a greyscale16 format but it is not. 

### Steps To Reproduce:
In a python3.7 environment:
```python
from gamera.core import *

def test(image):
    img = load_image(image)
    img2 = img.to_grey16()
    img2.save_PNG("out.png")

if __name__ == "__main__":
    image = "TODO: EDIT THE INPUT_PATH"
    init_gamera()
    test(image)
```
You can try testing the script using the following input RGB image.
![ConvertRGBImageToGrayscaleImageExample_01](https://user-images.githubusercontent.com/77243080/171201208-ae07d8bf-f977-4ec6-83fd-6a1ed12a4e50.png)

### Environment:
- M1 Mac python 3.7
- Debian Linux 5.10.104 python3.7

**Comment by cdalitz** [comment]
Strangely, the image is displayed correctly in the gamera_gui, even after saving it to a file and reloading that file. There seems to be some wrong usage of libpng in Gamera, maybe setting the header wrong. We must have a look into this.
