### ISSUE TITLE
🐞 cknn.group_and_update_list_automatic Assertion error when used for NonInteractive classifier

### ISSUE THREAD

**Issue by EMZEDI** [hsnr-gamera/gamera-4#49]
# name: 🐞 cknn.group_and_update_list_automatic used for NonInteractive Classifier AssertionError Bug
## Current Behavior:

I am using Gamera4 to classify 2 xml inputs using the NonInteractive classifier. When the code runs  cknn.group_and_update_list_automatic there is an assertion error looking like this:
```
File "/usr/local/lib/python3.7/dist-packages/gamera/classify.py", line 159, in group_and_update_list_automatic
    added, removed = self.group_list_automatic(glyphs, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gamera/classify.py", line 145, in group_list_automatic
    G = self._pregroup(glyphs, grouping_function)
  File "/usr/local/lib/python3.7/dist-packages/gamera/classify.py", line 171, in _pregroup
    assert G.has_node(glyph)
AssertionError
```
My guess is that the error is coming from how glyphs are added as nodes of a graph because the same code is run in python2 and Gamera3 but fails in python3 and Gamera4. 
## Expected Behavior:

The ```assert G.has_node(glyph)``` snippet must return True.

## Steps To Reproduce:

In a python3.7 environment:
1. Add a tester.py file with the following code to {YOUR_WORKING_DIRECTORY} (make sure you have the dependencies in the import statements installed) and replace {YOUR_WORKING_DIRECTORY} with the path of your working directory inside the python code.
```python
import os
from shutil import copyfile
import gamera.core
import gamera.gamera_xml
import gamera.classify
import gamera.knn
from gamera.gamera_xml import glyphs_from_xml
import tempfile
import shutil

tempdir="{YOUR_WORKING_DIRECTORY}/tmp"
classifier_path = "{YOUR_WORKING_DIRECTORY}/Interactive Classifier - GameraXML - Training Data Jan 19 (1).xml"
tempPath = os.path.join(tempdir, classifier_path + '.xml')
copyfile(classifier_path, tempPath)

cknn = gamera.knn.kNNNonInteractive(tempPath)

print(("cknn variable created from the knn.kNNNonInteractive is: {0} and has type: {1}").format(cknn, type(cknn)))

func = gamera.classify.BoundingBoxGroupingFunction(4)

print(("func coming from classify.BoundingBoxGroupingFunction with input 4 is: {0} and has type: {1}").format(func, type(func)))

print(("func has attributes theshold: {0} and function: {1}").format(func._threshold, func._function))

ccs = glyphs_from_xml('{YOUR_WORKING_DIRECTORY}/CC Analysis - GameraXML - Connected Components.xml')

print(("ccs created from the \" glyphs from xml method \" is: {0} and has type: {1}").format(ccs, type(ccs)))

cs_image = cknn.group_and_update_list_automatic(ccs,
                                        grouping_function=func,
                                        max_parts_per_group=4,
                                        max_graph_size=16)

# Generate the Gamera features
cknn.generate_features_on_glyphs(cs_image)
# Write the glyphs to GameraXML
output_xml = gamera.gamera_xml.WriteXMLFile(glyphs=cs_image,
                                    with_features=True)

output_xml.write_filename("{YOUR_WORKING_DIRECTORY}/output.xml")
```
2. Add a directory called tmp to {YOUR_WORKING_DIRECTORY}
3. Unzip the following files and add them to {YOUR_WORKING_DIRECTORY}:
[Archive 2.zip](https://github.com/hsnr-gamera/gamera-4/files/9047925/Archive.2.zip)
4. Run the script.

## Environment:

M1 Mac python 3.7
Debian Linux 5.10.104 python3.7
Windows with Intel chip python 3.7

**Comment by EMZEDI** [comment]
Hello,
I have **fixed** the _issue_ and will create a PR soon with full explanation.
For now, briefly:

- Last index of the list of the glyphs generated from the inputs above can't be added to the G graph as a node and generates an assertion error which I consider is coming from the changes made to Graph API inside the C++ modules.
- A similar error (C++ returning NULL) is generated inside the ```G.optimize_partitions``` function and must be caught using try/catch and passed (because the NULL does not affect the output of the function)

I am currently finalizing the changes to the code and will let you know once it is finished.

**Comment by EMZEDI** [comment]
📝 Issue Fixed in PR #50 
Full explanation can be found there.

**Comment by cdalitz** [comment]
Thanks for the suggestion for a fix, which unfortunately only is a workaround.

Eventually, I was able to find the actual couse for this problem, which was the use of the Python2 function `PyObject_Compare` instead of `PyObject_RichCompareBool` in *include/graph/graphdataderived.hpp*.

I have pushed my fix into git. Please let me know whether this solves your issue (your test example works now).

**Comment by cdalitz** [comment]
Just tested your workaround, and it does not help on my computer: the unit tests related to grouping still fail in the *tests* directory. Unfortunately, my fic didn't help either.

I wonder why it ever worked: As "value" in the graph, the CCs are used, which are images, and what should the comparison operator "<" return for an image? I did not even find it implmented in the Gamera code. Weird.

It might be the cleanest solution to use the indices of the glyph list as "values" (i.e. identifiers) in the graph, because integers are comparable.

**Comment by cdalitz** [comment]
Argh! Eventually I found the error. The comparison operator `__lt__` for images was wrongly implemented in *gamera/core.py* as the negation  of `__gt__` instead of `__ge__`.

This is fixed now and I think the issue is solved. Please confirm this.

**Comment by EMZEDI** [comment]
Hello. 
Apologies for the delay. Yes I tested the script and it works!
Thanks for the fix.
