### ISSUE TITLE
Publish on PyPI?

### ISSUE THREAD

**Issue by FriedrichFroebel** [hsnr-gamera/gamera-4#65]
I would like to see *gamera* to be available on PyPI (which is why I just submitted PR #64 to at least complete the basic information). This should improve the installation experience for packages which depend on *gamera* and which have to rely on GitHub-based installations at the moment.

Unfortunately, this is currently blocked by an existing package under the same name by an (unknown?) user `Glass.Cube`, which only provides a Windows binary for Python 2.7 and *gamera* version 3.3.3, uploaded in 2012. To take over the package, it seems like https://peps.python.org/pep-0541/#how-to-request-a-name-transfer applies (the URL points to the general *gamera* webpage at HSNR and there is no public contact address as far as I am aware).

Is there any interest on your side to tackle this? Alternatively, if it is okay for you, I would try to work on this myself.

**Comment by cdalitz** [comment]
Yes, please have a look into this. Thanks for taking the trouble.

Does the availability on PyPI create maintenance issues in the future?

**Comment by FriedrichFroebel** [comment]
> Does the availability on PyPI create maintenance issues in the future?

There should be no general overhead when doing this. The only additional step is pushing the source distribution to PyPI on each release, which is easy to automate or to do manually.

**Comment by cdalitz** [comment]
_pushing the source distribution to PyPI_
Do you have some documentation how to do this?

**Comment by FriedrichFroebel** [comment]
The official documentation is available at https://packaging.python.org/en/latest/tutorials/packaging-projects/. The easiest way could look like this:

1. `python3 setup.py sdist`
2. `python3 -m twine upload dist/*`

**Comment by FriedrichFroebel** [comment]
It took its time, but the *gamera* project on PyPI has finally been transferred to my account.

I will have to do some tests and would upload the official ` gamera-4.1.0.tar.gz` source distribution there if I observe no issues during testing. Of course, I am open to provide access to the PyPI project for the actual maintainers/group members as well.

**Comment by FriedrichFroebel** [comment]
Version 4.1.0 is now available as a source distribution from PyPI and I could successfully build and install it with the usual `pip install gamera`.
